# Generated by Django 2.0.2 on 2018-04-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('compteid', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('classe', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('users_usersid', models.IntegerField()),
            ],
            options={
                'db_table': 'contrat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('creditid', models.AutoField(primary_key=True, serialize=False)),
                ('operation_operationid', models.IntegerField()),
                ('compte_compteid', models.IntegerField()),
                ('operation_typejournal_typejournalid', models.IntegerField()),
                ('operation_travailleur_users_usersid', models.IntegerField(db_column='operation_TRAVAILLEUR_users_usersid')),
                ('operation_piece_pieceid', models.IntegerField()),
                ('operation_travailleur_travailleurid', models.IntegerField()),
                ('montant', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Debits',
            fields=[
                ('debitsid', models.AutoField(primary_key=True, serialize=False)),
                ('operation_operationid', models.IntegerField()),
                ('compte_compteid', models.IntegerField()),
                ('operation_typejournal_typejournalid', models.IntegerField()),
                ('operation_travailleur_users_usersid', models.IntegerField(db_column='operation_TRAVAILLEUR_users_usersid')),
                ('operation_piece_pieceid', models.IntegerField()),
                ('operation_travailleur_travailleurid', models.IntegerField()),
                ('montant', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'debits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dfe',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('users_usersid', models.IntegerField()),
            ],
            options={
                'db_table': 'dfe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dsv',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('users_usersid', models.IntegerField()),
            ],
            options={
                'db_table': 'dsv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operationid', models.AutoField(primary_key=True, serialize=False)),
                ('typejournal_typejournalid', models.IntegerField()),
                ('travailleur_users_usersid', models.IntegerField()),
                ('piece_pieceid', models.IntegerField()),
                ('travailleur_travailleurid', models.IntegerField()),
                ('libelle', models.CharField(blank=True, max_length=45, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('dateoperation', models.DateField(blank=True, null=True)),
                ('datesaisie', models.DateField(blank=True, null=True)),
                ('travailleuridsaisie', models.IntegerField(blank=True, null=True)),
                ('travailleuridimpute', models.IntegerField(blank=True, db_column='travailleurIdimpute', null=True)),
                ('typejournalid', models.IntegerField(blank=True, null=True)),
                ('pieceid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('pieceid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=45, null=True)),
                ('typepieceid', models.IntegerField(blank=True, null=True)),
                ('lien', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'piece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('users_usersid', models.IntegerField()),
                ('denomination', models.CharField(blank=True, max_length=45, null=True)),
                ('siege', models.CharField(blank=True, max_length=45, null=True)),
                ('objet', models.CharField(blank=True, max_length=45, null=True)),
                ('capital', models.FloatField(blank=True, null=True)),
                ('durée', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'statut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Travailleur',
            fields=[
                ('travailleurid', models.AutoField(primary_key=True, serialize=False)),
                ('users_usersid', models.IntegerField()),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('prenom', models.CharField(blank=True, max_length=45, null=True)),
                ('fonction', models.CharField(blank=True, max_length=45, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'travailleur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Typejournal',
            fields=[
                ('typejournalid', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'typejournal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Typepiece',
            fields=[
                ('typepieceid', models.AutoField(db_column='typepieceId', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'typepiece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('usersid', models.AutoField(primary_key=True, serialize=False)),
                ('denomination', models.CharField(blank=True, max_length=45, null=True)),
                ('siege', models.CharField(blank=True, max_length=45, null=True)),
                ('objet', models.CharField(blank=True, max_length=45, null=True)),
                ('capital', models.CharField(blank=True, max_length=45, null=True)),
                ('duree', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
